module.exports = [
    {
        id:1,
        name:"Akshay",
        age:28,
        email:"akki6666@gmail.com",
        empID:"tyu678",
    },
    {
        id: 2,
        name: "Ram",
        age: 58,
        email: "ram@gmail.com",
        empID: "mxui988",
    },
    {
        id: 3,
        name: "Sharan",
        age: 20,
        email: "ssgg@gmail.com",
        empID: "lif763",
    },
    {
        id: 4,
        name: "Lidia",
        age: 28,
        email: "lddd@gmail.com",
        empID: "lsad88",
    },
    {
        id: 5,
        name: "Rohan",
        age: 18,
        email: "asdf@gmail.com",
        empID: "tyu6ads78",
    },
    {
        id: 6,
        name: "ashu",
        age: 29,
        email: "ashu@gmail.com",
        empID: "gfyu678",
    },
    {
        id: 7,
        name: "Vishnu",
        age: 22,
        email: "aas@gmail.com",
        empID: "wyu608",
    },
    {
        id: 8,
        name: "Josh",
        age: 62,
        email: "josh6@gmail.com",
        empID: "jadas86",
    },
    {
        id: 9,
        name: "Mike",
        age: 31,
        email: "mike@gmail.com",
        empID: "sas678",
    },
    {
        id: 10,
        name: "Nick",
        age: 38,
        email: "aasdsd@gmail.com",
        empID: "tyuas48",
    },
]